package deploy

import (
	"bytes"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pablo-botella/mkskill/compiler"
)

// TestDeploy runs the whole chain on a working copy of the demo fixture and
// checks what lands on disk: the preserved README written under its alias,
// AGENTS.md and the root skill in their places, and the child — default
// artifacts — writing only its README.
func TestDeploy(t *testing.T) {
	base := filepath.Join("..", "_out", "deploy", "demo")
	if err := os.RemoveAll(filepath.Join("..", "_out", "deploy")); err != nil {
		t.Fatal(err)
	}
	copyTree(t, filepath.Join("..", "_data", "demo"), base)

	root := &compiler.Root{ProjectBase: base}
	if err := root.Load(); err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	for _, phase := range []func(io.Writer) error{root.Scan, root.Prepare, root.Resolve, root.Deploy} {
		if err := phase(&buf); err != nil {
			t.Fatal(err)
		}
	}
	logs := buf.String()

	// the root README is preserved with method alias: mkskill's version
	// lands next to it under the alias name, the original stays unwritten
	if _, err := os.Stat(filepath.Join(base, "README.md")); err == nil {
		t.Error("preserved README.md was written")
	}
	alias := mustRead(t, filepath.Join(base, "readme-alt.md"))
	if !strings.Contains(alias, "# Demo overview") {
		t.Errorf("readme-alt.md misses the composed content:\n%s", alias)
	}

	agents := mustRead(t, filepath.Join(base, "AGENTS.md"))
	if !strings.Contains(agents, "# Demo overview") {
		t.Errorf("AGENTS.md misses the composed content:\n%s", agents)
	}

	skill := mustRead(t, filepath.Join(base, ".claude", "skills", "demo", "SKILL.md"))
	if !strings.HasPrefix(skill, "---\nname: demo\ndescription: demo\n---\n\n") {
		t.Errorf("SKILL.md misses its wrapper:\n%s", skill)
	}
	if !strings.Contains(skill, "# Demo overview") {
		t.Errorf("SKILL.md misses the composed content:\n%s", skill)
	}

	// the child has no artifacts attribute: only its README is its own
	if got := mustRead(t, filepath.Join(base, "cmd", "tool", "README.md")); !strings.Contains(got, "# Tool CLI") {
		t.Errorf("child README.md wrong:\n%s", got)
	}

	// global-artifacts="agents,skill": the PARENT's views land under the
	// child's base too — the skill keeps the parent's identity
	if got := mustRead(t, filepath.Join(base, "cmd", "tool", "AGENTS.md")); !strings.Contains(got, "# Demo overview") {
		t.Errorf("child AGENTS.md should carry the parent's views:\n%s", got)
	}
	if got := mustRead(t, filepath.Join(base, "cmd", "tool", ".claude", "skills", "demo", "SKILL.md")); !strings.HasPrefix(got, "---\nname: demo\n") {
		t.Errorf("child global SKILL.md wrong:\n%s", got)
	}

	// the child declares an embed (no embed-parent): its own views land as
	// files under mkskill_docs/ and //go:embed strings fill the Spec
	embed := mustRead(t, filepath.Join(base, "cmd", "tool", "demo_embed.go"))
	for _, want := range []string{
		"// Code generated by mkskill. DO NOT EDIT.",
		"package main",
		"//go:embed mkskill_docs/README.md",
		"//go:embed mkskill_docs/SKILL.md",
		"var mkskillReadme string",
		"var MkskillSpec = mkskill.Spec{",
		"\tName:        \"tool\",",
		"\tSkill:       mkskillSkill,",
	} {
		if !strings.Contains(embed, want) {
			t.Errorf("demo_embed.go misses %q:\n%s", want, embed)
		}
	}
	if docs := mustRead(t, filepath.Join(base, "cmd", "tool", "mkskill_docs", "README.md")); !strings.Contains(docs, "# Tool CLI") {
		t.Errorf("mkskill_docs/README.md misses the composed content:\n%s", docs)
	}

	for _, want := range []string{
		"[main] deploy README.md: preserved, using alias readme-alt.md",
		"[main] deploy readme-alt.md: ",
		"[main] deploy AGENTS.md: ",
		"[main] deploy .claude/skills/demo/SKILL.md: ",
		"[cli] deploy AGENTS.md: not an artifact of this unit",
		"[cli] deploy SKILL.md: not an artifact of this unit",
		"[cli] deploy README.md: ",
		"[cli] global artifact AGENTS.md: views of main",
		"[cli] global artifact SKILL.md: views of main",
		"[cli] deploy .claude/skills/demo/SKILL.md: ",
		"[cli] embed demo_embed.go + mkskill_docs/ (views of cli: README.md AGENTS.md SKILL.md)",
	} {
		if !strings.Contains(logs, want) {
			t.Errorf("log misses %q:\n%s", want, logs)
		}
	}
}

// TestGlobalCollision checks the collision guard: a child deploying its own
// agents AND asking for the parent's gets a warning — the first write (its
// own) stands.
func TestGlobalCollision(t *testing.T) {
	base := filepath.Join("..", "_out", "deploy", "collision")
	if err := os.RemoveAll(base); err != nil {
		t.Fatal(err)
	}
	files := map[string]string{
		"_mkskill/mkskill.config.xml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
			"<mkskill>\n" +
			"  <project id=\"m\" name=\"demo\" project-type=\"Other\">\n" +
			"    <child-project id=\"c\" name=\"tool\" path=\"./cmd/tool\" project-type=\"Other\"" +
			" artifacts=\"readme,agents\" global-artifacts=\"agents\"/>\n" +
			"  </project>\n" +
			"</mkskill>\n",
		"_mkskill/src/a.md":          "# Root\n",
		"cmd/tool/_mkskill/src/b.md": "# Tool\n",
	}
	for file, content := range files {
		target := filepath.Join(base, filepath.FromSlash(file))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(target, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	root := &compiler.Root{ProjectBase: base}
	if err := root.Load(); err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	for _, phase := range []func(io.Writer) error{root.Scan, root.Prepare, root.Resolve, root.Deploy} {
		if err := phase(&buf); err != nil {
			t.Fatal(err)
		}
	}

	if got := mustRead(t, filepath.Join(base, "cmd", "tool", "AGENTS.md")); !strings.Contains(got, "# Tool") {
		t.Errorf("the child's own AGENTS.md should stand:\n%s", got)
	}
	if want := "[c] WARN: AGENTS.md collides with an artifact already deployed, not written"; !strings.Contains(buf.String(), want) {
		t.Errorf("log misses %q:\n%s", want, buf.String())
	}
}

// TestDeployAltMirror checks the alt method's second half: the preserved
// destination stays untouched and mkskill's version lands in the
// _mkskill/alt/files/ mirror, gitignored as every alt compartment.
func TestDeployAltMirror(t *testing.T) {
	base := filepath.Join("..", "_out", "deploy", "alt-mirror")
	if err := os.RemoveAll(base); err != nil {
		t.Fatal(err)
	}
	files := map[string]string{
		"_mkskill/mkskill.config.xml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
			"<mkskill>\n" +
			"  <project id=\"m\" name=\"demo\" project-type=\"Other\">\n" +
			"    <preserve><item file=\"./AGENTS.md\"/></preserve>\n" +
			"  </project>\n" +
			"</mkskill>\n",
		"_mkskill/src/a.md": "# Root\n",
		"AGENTS.md":         "hand-made, hands off\n",
	}
	for file, content := range files {
		target := filepath.Join(base, filepath.FromSlash(file))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(target, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	root := &compiler.Root{ProjectBase: base}
	if err := root.Load(); err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	for _, phase := range []func(io.Writer) error{root.Scan, root.Prepare, root.Resolve, root.Deploy} {
		if err := phase(&buf); err != nil {
			t.Fatal(err)
		}
	}

	if got := mustRead(t, filepath.Join(base, "AGENTS.md")); got != "hand-made, hands off\n" {
		t.Errorf("preserved AGENTS.md was touched: %q", got)
	}
	mirror := filepath.Join(base, "_mkskill", "alt", "files", "AGENTS.md")
	if got := mustRead(t, mirror); !strings.Contains(got, "# Root") {
		t.Errorf("mirror misses mkskill's version:\n%s", got)
	}
	if got := mustRead(t, filepath.Join(base, "_mkskill", "alt", "files", ".gitignore")); got != "*\n!.gitignore\n" {
		t.Errorf("alt/files .gitignore wrong: %q", got)
	}
	if want := "[m] deploy AGENTS.md: preserved (alt), mkskill's version to _mkskill/alt/files/AGENTS.md"; !strings.Contains(buf.String(), want) {
		t.Errorf("log misses %q:\n%s", want, buf.String())
	}
}

// copyTree clones the fixture into the working area, file by file.
func copyTree(t *testing.T, src, dst string) {
	t.Helper()
	err := filepath.WalkDir(src, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if entry.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644)
	})
	if err != nil {
		t.Fatal(err)
	}
}

func mustRead(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
