// Code generated by mkskill. DO NOT EDIT.

package main

import (
	_ "embed"

	"github.com/pablo-botella/mkskill"
)

//go:embed mkskill_docs/README.md
var mkskillReadme string

//go:embed mkskill_docs/AGENTS.md
var mkskillAgents string

//go:embed mkskill_docs/SKILL.md
var mkskillSkill string

// MkskillSpec carries the composed documentation views, ready for the
// generate commands (mkskill.CheckParams and friends).
var MkskillSpec = mkskill.Spec{
	Name:        "mkskill",
	Description: "Compose README.md, AGENTS.md and the Claude Code SKILL.md from one markdown source under _mkskill/.",
	Version:     "v0.5.4",
	Readme:      mkskillReadme,
	Agents:      mkskillAgents,
	Skill:       mkskillSkill,
}
