package compiler

import (
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"
)

// _EmbedDocsFolder is where the composed views land for //go:embed: next to
// the generated file (go:embed cannot reach outside the package folder) and
// with no leading underscore (go:embed skips _* patterns).
const _EmbedDocsFolder = "mkskill_docs"

// deployEmbed writes the unit's generated Go embed, when it declares one:
// the composed views land as real files under mkskill_docs/ next to the
// generated source, which //go:embed's them straight into strings filling a
// mkskill.Spec — the host binary carries its documentation and handles the
// generate commands itself (mkskill.CheckParams and friends). embed-parent
// selects which of the PARENT's views ride along ("*" or a comma list);
// without it the unit embeds its own views, all of them.
func (p *Project) deployEmbed(log io.Writer) error {
	e := p.Embed
	if e == nil {
		return nil
	}
	// the config was refused at LOAD if the embed had no filename or an
	// embed-parent without a parent (validateRenders) — here both hold
	fname := e.Filename.Get() // the render: expandables resolve at load
	module := e.ModuleName.Get()
	if module == "" {
		module = "main" // the natural host: a cmd's package
	}

	source, selection := p, e.EmbedParent.Get()
	if selection != "" {
		source = p.Parent
	} else {
		selection = "*"
	}
	selected := func(name string) bool {
		for tok := range strings.SplitSeq(selection, ",") {
			if tok = strings.TrimSpace(tok); tok == "*" || tok == name {
				return true
			}
		}
		return false
	}

	// the docs folder lives next to the generated file; a fresh one every
	// run — its content is all artifact
	fileRel := filepath.FromSlash(fname)
	docsRel := path.Join(path.Dir(fname), _EmbedDocsFolder)
	docsAbs := filepath.Join(p.Base, filepath.FromSlash(docsRel))
	if err := os.RemoveAll(docsAbs); err != nil {
		return err
	}

	specVars := [3]string{"Readme", "Agents", "Skill"}
	embedVars := [3]string{"mkskillReadme", "mkskillAgents", "mkskillSkill"}
	var written []string
	var vars, fields strings.Builder
	field := func(name, value string) {
		fmt.Fprintf(&fields, "\t%-12s %s,\n", name+":", value)
	}
	field("Name", strconv.Quote(string(source.Name)))
	field("Description", strconv.Quote(source.MetaValue("description")))
	if !e.EmbedVersion.Empty() {
		// already resolved at load, in this unit's own scope: the render
		// is what the binary carries and the version command prints
		field("Version", strconv.Quote(e.EmbedVersion.Get()))
	}
	for i := range Views {
		v := &Views[i]
		if !selected(v.Name) {
			continue
		}
		doc, err := source.Compose(log, v)
		if err != nil {
			return err
		}
		if doc == "" {
			continue
		}
		if len(written) == 0 {
			if err := os.MkdirAll(docsAbs, 0o755); err != nil {
				return err
			}
		}
		if err := os.WriteFile(filepath.Join(docsAbs, v.FileName), []byte(doc), 0o644); err != nil {
			return err
		}
		written = append(written, v.FileName)
		vars.WriteString("//go:embed " + _EmbedDocsFolder + "/" + v.FileName + "\n")
		vars.WriteString("var " + embedVars[i] + " string\n\n")
		field(specVars[i], embedVars[i])
	}

	var b strings.Builder
	b.WriteString("// Code generated by mkskill. DO NOT EDIT.\n\n")
	b.WriteString("package " + module + "\n\n")
	b.WriteString("import (\n\t_ \"embed\"\n\n\t\"github.com/pablo-botella/mkskill\"\n)\n\n")
	b.WriteString(vars.String())
	b.WriteString("// MkskillSpec carries the composed documentation views, ready for the\n")
	b.WriteString("// generate commands (mkskill.CheckParams and friends).\n")
	b.WriteString("var MkskillSpec = mkskill.Spec{\n")
	b.WriteString(fields.String())
	b.WriteString("}\n")

	abs := filepath.Join(p.Base, fileRel)
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(abs, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(log, "[%s] embed %s + %s/ (views of %s: %s)\n",
		p.Id, fname, docsRel, source.Id, strings.Join(written, " "))
	return nil
}
